server:
  port: 8001

spring:
  application:
    name: microservice-product
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springcloud_db01?serverTimeZone=GMT%2B8
    username: root
    password: password
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 150
  jpa:
    show-sql: true


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:6001/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true