server:
  port: 8002

spring:
  application:
    name: microservice-user
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springcloud_db02?serverTimeZone=GMT%2B8
    username: root
    password: password
  jpa:
    show-sql: true

  queries:
    users-query: select email, password, active from users where email=?
    roles-query: select email, role from users where email=?

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:6001/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true

jwt:
  header: Authorization
  secret: my-very-secret-key

jwtSecret: tommy
jwtExpiration: 123456